name: Github Actions for Sagemaker polling
on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    if: ${{ github.event.client_payload.passed }} == Failed
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
  run_if_success:
    if: ${{ github.event.client_payload.passed }} == Succecced
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
  run_if_executing:
    if: ${{ github.event.client_payload.passed }} == Executing
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
