name: Github Actions for Sagemaker polling
on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.status }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: |
          echo $MESSAGE
          exit 1
  run_if_success:
    if: ${{ github.event.client_payload.status }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The pipeline ran successfully"

            

