name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Get Current Job Log URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: Explore-GitHub-Actions
        per_page: 30
    - name: Output Current Job Log URL
      run: |
        echo ${{ steps.jobs.outputs.html_url }}
        exit 1
      
