name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  Pipeline_exectuion:
    name: Pipeline_exectuion
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: echo "Pipeline submitted succeessfully"
     
  Status_check_execution:
    name: Status check execution
    needs: Pipeline_exectuion
    runs-on: ubuntu-latest
    steps:
    - name : get the status
      run: Aws dynamo db get item from table where excution arn = fetch arn.output varible and github run ID= $ github.runID
           if value blank insert item
           else if status is success  exit 0
           else exit 1
    - name: Get Current Job Log URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: Status check execution
        per_page: 30
    - name: Output Current Job Log URL
      run: |
        echo ${{ steps.jobs.outputs.html_url }}
        echo ${{ steps.jobs.outputs.url }}
        echo ${{ steps.jobs.outputs}}
        exit 1
      
      
